### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Botasha/prj-rev-bwfs-dasmoto#8]
https://github.com/Botasha/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Art%20%26%20Craft/Resources/CSS/index.css#L1-L20

This is unreadable.

Resist the urge to write your CSS rules in a single line. Even for a simple rule with only a single property, write it like so:

```css
selector {
  property: value;
}
```
